PROMPT '=== VERIFICATION DES DONNEES ===';

SELECT 'AGENCES' as TABLE_NAME, COUNT(*) as NB_ENREGISTREMENTS FROM Agence
UNION ALL
SELECT 'PROPRIETAIRES', COUNT(*) FROM Proprietaire
UNION ALL
SELECT 'IMMEUBLES', COUNT(*) FROM Immeuble
UNION ALL
SELECT 'APPARTEMENTS', COUNT(*) FROM Appartement
UNION ALL
SELECT 'LOCATAIRES', COUNT(*) FROM Locataire
UNION ALL
SELECT 'RELATIONS_APPARTENIR', COUNT(*) FROM Appartenir
UNION ALL
SELECT 'RELATIONS_LOUER', COUNT(*) FROM Louer
UNION ALL
SELECT 'RELATIONS_GERER', COUNT(*) FROM Gerer;